version: "3.9"

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ELASTIC_PASSWORD: MyPassword123!
    ports:
      - 9200:9200
